spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:log4jdbc:mysql://localhost:3306/springboot?useSSL=false&characterEncoding=utf8
    username: root
    password: jilinwula
    driver-class-name: net.sf.log4jdbc.DriverSpy
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

